name: Publish GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          output-dir: dist
          allow-local-files: true
          generate-html: true
          options: --html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: dist
